logging:
  level:
    root: INFO
    ru.yandex.practicum: INFO
    org.zalando.logbook: TRACE

spring:
  boot:
    build-info:
      package-classpath: true
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password

app:
  admin:
    email: ${ADMIN_EMAIL:admin@filmorate.local}
    login: ${ADMIN_LOGIN:admin}
    name: ${ADMIN_NAME:Administrator}
    birthday: ${ADMIN_BIRTHDAY:1990-01-01}
    password: ${ADMIN_PASSWORD:admin123}